export * from './Home'
export * from './Error404'
export * from './Tests'
export * from './Product'
export * from './Checkout'
export * from './Singup'
export * from './Login'
export * from './ForgotPassword'
